FROM python:3.11

WORKDIR /app

COPY requirements_torch.txt .
COPY requirements_tft.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_torch.txt --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r requirements_tft.txt