FROM python:3.8

WORKDIR /app

COPY requirements_DataDL.txt .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_DataDL.txt

COPY main_DataDL.py .

CMD ["python", "-u", "main_DataDL.py"]